sudo: false
language: cpp
compiler:
  clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - clang-3.9
      - clang-format-3.9

script:
  - export CC=clang-3.9 CXX=clang++3.9
  - rm -f /usr/local/bin/clang-format; ln -s $(which clang-format3.9) /usr/local/bin/clang-format
  - ./run format
  - if [[ -n $(git status --porcelain) ]]; then \
      echo "make sure the code is formatted."   \
      exit 1                                    \
    else                                        \
      exit 0                                    \
    fi

notifications:
  email: false
